version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/groep-3-there/backend:feature-DS39-environments
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  frontend:
    image: ghcr.io/groep-3-there/frontend:develop
    ports:
      - '3000:80'
    depends_on:
      - backend
volumes:
  postgres-data:

#RUN USING:
#docker-compose down
#docker-compose pull
#docker-compose up --build