name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Clean the database
    - uses: actions/checkout@v2
    - uses: liquibase/liquibase-github-action@v7
      with:
        operation: 'update'
        classpath: 'example/changelogs'
        changeLogFile: 'samplechangelog.h2.sql'
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        url: ${{ secrets.URL }}
      run: mvn liquibase:dropAll -Djasypt.encryptor.password=${{ secrets.SECRET_KEY }}
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'temurin'
        cache: maven
    - name: Run and Stop Spring Boot
      run: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Djasypt.encryptor.password=${{ secrets.SECRET_KEY }} -Dspring.profiles.active=dev" & sleep 30 && mvn spring-boot:stop
    - name: build and test
      run: mvn clean install -Djasypt.encryptor.password=${{ secrets.SECRET_KEY }}
